### ISSUE TITLE
Dead?

### ISSUE THREAD

**Issue by Talcon2** [pieper/dicomzoo#2]
Did this effort continue elsewhere, or was the idea dropped?

**Comment by pieper** [comment]
it's not dead but we haven't found a good way to put it into action yet.  My current feeling is that we might be able to use one of the static dicomweb hosting options [like this one](https://github.com/RadicalImaging/static-dicomweb) so that it's cheap to host example data out of cloud buckets.

**Comment by Talcon2** [comment]
If there is anyway I can assist, Id be more than happy to.

**Comment by pieper** [comment]
> If there is anyway I can assist, Id be more than happy to.

That would be great!  I'm open to ideas of things you think would help.  One thing that comes to mind would be to collect more links to public data that could be included.

More ambitious would be to set up some kind of testing mechanism so that various toolkits could be tested against all or parts of the zoo data to test consistency.  E.g. to confirm that implementations in C, C++, java, C#, javascript, etc all handle data consistently.  Ideally this could be set up in some kind of dashboard so that edge cases or software regressions could be tracked down and crosslinked to issues and PRs.  It would be cool if this kind of a testing framework could be containerized so that it would be easy for people to run it even on local data that they can't share but they could still post results to a dashboard for tracking consistency across packages.

**Comment by Talcon2** [comment]
For the links to public data, are you looking for static pages with download links like Aliza? Or are you looking to include publicly hosted dicom servers like https://www.dicomserver.co.uk/ also?

For testing for consistency, what would be the parameters for that, to ensure invalid DICOM is flagged as invalid across languages?

**Comment by pieper** [comment]
> For the links to public data, are you looking for static pages with download links like Aliza? Or are you looking to include publicly hosted dicom servers like https://www.dicomserver.co.uk/ also?

I would want to try to host them all consistently, like in s3 buckets, so that there wouldn't be issues with servers going off line or files being renamed.  So basically any sources of publicly shareable data would be good. 


> For testing for consistency, what would be the parameters for that, to ensure invalid DICOM is flagged as invalid across languages?

I think we would start with something like checking that all toolkits give the same pixel data values and if they didn't it would be an issue that needs to be tracked down to figure out which are right and wrong and file issues with the maintainers of the toolkits.  There could be similar tests for other required header fields.  For specific instance types there may be special tests to check how optional or conditional header elements are handled.
